# Generated by Django 5.1.15 on 2026-02-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_role_image_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
