# Generated by Django 5.1.15 on 2026-02-22 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dark_mode', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('auto_email_reports', models.BooleanField(default=True)),
            ],
        ),
    ]
