# Generated by Django 5.1.15 on 2026-02-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserPreferences',
        ),
    ]
