# Generated by Django 5.1.15 on 2026-04-03 07:10

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Unique identifier for this class, used for internal reference and user-friendly reporting. Case-insensitive. For example: 'ser401-fall-2026 A' or 'Social Studies 2026 B Alexander'. This field must be unique across all classes and must not be blank.", max_length=255)),
                ('name', models.CharField(help_text='The human-readable name of this class, as displayed to users', max_length=128)),
                ('timeframe', models.CharField(blank=True, help_text='Optional timeframe for the class, if more specificity than year is needed e.g. Fall, Spring, etc.', max_length=32)),
                ('year', models.IntegerField(blank=True, help_text='Optional year for the class, e.g. 2024', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)])),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_classrooms', to='classroom.assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='classroom.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='classrooms', through='classroom.ClassroomAssignment', to='classroom.assignment'),
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_override', models.IntegerField(blank=True, choices=[(0, 'OBSERVER'), (1, 'STUDENT'), (2, 'TEACHER'), (3, 'SUPERUSER')], help_text="Overrides a user's global role for this class", null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classroom.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='members',
            field=models.ManyToManyField(related_name='enrolled_classes', through='classroom.ClassroomMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('major_version', models.PositiveIntegerField(default=1)),
                ('minor_version', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
                ('problems', models.ManyToManyField(blank=True, related_name='assignment_versions', to='classroom.problem')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_reports', to='classroom.assignment')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_reports', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReportProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='classroom.problem')),
                ('student_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_problems', to='classroom.studentreport')),
            ],
        ),
        migrations.AddField(
            model_name='studentreport',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='student_reports', through='classroom.StudentReportProblem', to='classroom.problem'),
        ),
        migrations.AddConstraint(
            model_name='classroomassignment',
            constraint=models.UniqueConstraint(fields=('classroom', 'assignment'), name='unique_assignment_per_classroom'),
        ),
        migrations.AddConstraint(
            model_name='classroommembership',
            constraint=models.UniqueConstraint(fields=('user', 'classroom'), name='unique_user_classroom_membership'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('identifier'), name='unique_classroom_identifier_ci'),
        ),
        migrations.AddConstraint(
            model_name='assignmentversion',
            constraint=models.UniqueConstraint(fields=('assignment', 'major_version', 'minor_version'), name='unique_assignment_version'),
        ),
    ]
