# Generated by Django 5.1.15 on 2026-03-16 17:52

from django.db import migrations

def seed_topic_reference_data(apps, schema_editor):
    # Fetch the Topic model from the current app registry
    Topic = apps.get_model('math_tutor', 'Topic')
    
    Topic.objects.bulk_create([
      Topic(value="linear equations in slope-intercept form (y = mx + b)"),
      Topic(value="linear equations in point-slope form"),
      Topic(value="linear equations in standard form (Ax + By = C)"),
      Topic(value="finding slope from two points"),
      Topic(value="finding slope from a graph"),
      Topic(value="parallel and perpendicular lines"),
      Topic(value="quadratic equations and parabolas"),
      Topic(value="factoring quadratic expressions"),
      Topic(value="solving quadratic equations by factoring"),
      Topic(value="quadratic formula"),
      Topic(value="completing the square"),
      Topic(value="systems of linear equations"),
      Topic(value="solving systems by substitution"),
      Topic(value="solving systems by elimination"),
      Topic(value="linear inequalities"),
      Topic(value="systems of inequalities"),
      Topic(value="polynomials (addition, subtraction, multiplication)"),
      Topic(value="factoring polynomials"),
      Topic(value="exponential functions"),
      Topic(value="absolute value equations"),
      Topic(value="rational expressions"),
      Topic(value="radical expressions"),
  ])


class Migration(migrations.Migration):

    dependencies = [
        ("math_tutor", "0001_topic"),
    ]

    operations = [
        migrations.RunPython(seed_topic_reference_data),
    ]
