# Generated by Django 5.1.15 on 2026-03-16 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("math_tutor", "0002_seed_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("llm_model", models.CharField(max_length=50)),
                ("user_content", models.TextField()),
                ("system_content", models.TextField()),
                (
                    "temperature",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
            ],
        ),
    ]
