# Generated by Django 5.1.15 on 2026-03-16 17:52

from django.db import migrations

def seed_chatmessage_reference_data(apps, schema_editor):
    # Fetch the Topic model from the current app registry
    ChatMessage = apps.get_model('math_tutor', 'ChatMessage')

    ChatMessage.objects.bulk_create([
        ChatMessage(slug="generate-math-problem",
                    llm_model="gpt-4o-mini",
                    user_content='''Generate a single Algebra 1 word problem about {topic}. 
The problem should:
- Be appropriate for Algebra 1 students
- Be a real-world scenario or application
- Include all necessary information to solve the problem
- Use clear, age-appropriate language
- Return only the problem text, no solutions, explanations, or equations in the problem text itself (the equation will be extracted separately)

Example format: "A car rental company charges a base fee of $25 plus $0.15 per mile driven. If you have a budget of $100, how many miles can you drive?"

Do NOT include equations like "y = mx + b" or "y = 25 + 0.15x" in the problem text itself - just describe the scenario.`''',
                    system_content="You are a helpful math teacher that creates Algebra 1 word problems. You create engaging, real-world problems that help students understand mathematical concepts.",
                    temperature=0.8)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("math_tutor", "0003_chatmessage"),
    ]

    operations = [
        migrations.RunPython(seed_chatmessage_reference_data),
    ]
