# Generated by Django 5.1.15 on 2026-03-16 17:52

from django.db import migrations

def seed_generate_hint_reference_data(apps, schema_editor):
    # Fetch the Topic model from the current app registry
    ChatMessage = apps.get_model('math_tutor', 'ChatMessage')

    ChatMessage.objects.bulk_create([
        ChatMessage(slug="generate-hint-1",
                    llm_model="gpt-4o-mini",
                    user_content='''You are a helpful math tutor. A student is working on this problem:

"{problem}"

Provide a detailed first hint that helps the student understand:
1. What type of problem this is (e.g., distance/rate/time, area, percentage, linear equation, system of equations, etc.)
2. What they're being asked to find
3. What information has been given to them
4. A general strategy or formula they should consider (mention the formula by name if applicable)

Be specific about the numbers and context in the problem, but don't solve it for them. Write 3-4 sentences.''',
                    system_content="You are an encouraging math tutor who provides clear, detailed hints. Be specific and use concrete examples from the problem. Never give the final answer, but guide students step-by-step. Use simple language and be thorough. IMPORTANT: Do NOT use LaTeX formatting. Do NOT use \\( \\), \\[ \\], $, or any backslash commands. Write all math using plain text with symbols like ×, ÷, ², ³, etc. For example, write 'w + 5' not '\\( w + 5 \\)', and write 'Area = length × width' not '\\text{Area} = \\text{length} \\times \\text{width}'. Write variables and numbers directly without any special formatting.",
                    temperature=0.7),

        ChatMessage(slug="generate-hint-2",
                    llm_model="gpt-4o-mini",
                    user_content='''You are a helpful math tutor. A student is working on this problem:

"{problem}"

They've already seen a general hint about the problem type and approach. Now provide a more detailed second hint that:
1. Explicitly states which formula or equation to use (write out the formula)
2. Identifies each variable in the formula
3. Shows which values from the problem correspond to which variables
4. Explains the next step they should take

Use the actual numbers from the problem and be very specific. Write 4-5 sentences.''',
                    system_content="You are an encouraging math tutor who provides clear, detailed hints. Be specific and use concrete examples from the problem. Never give the final answer, but guide students step-by-step. Use simple language and be thorough. IMPORTANT: Do NOT use LaTeX formatting. Do NOT use \\( \\), \\[ \\], $, or any backslash commands. Write all math using plain text with symbols like ×, ÷, ², ³, etc. For example, write 'w + 5' not '\\( w + 5 \\)', and write 'Area = length × width' not '\\text{Area} = \\text{length} \\times \\text{width}'. Write variables and numbers directly without any special formatting.",
                    temperature=0.7),

        ChatMessage(slug="generate-hint-3",
                    llm_model="gpt-4o-mini",
                    user_content='''You are a helpful math tutor. A student is working on this problem:

"{problem}"

They've seen two previous hints but still need help. Provide a comprehensive third and final hint that:
1. States the complete formula or equation needed
2. Shows the COMPLETE substitution with actual numbers from the problem (e.g., "speed = 120 km ÷ 2 hours")
3. Shows the mathematical expression ready to calculate (e.g., "= 120 ÷ 2")
4. Tells them what units the answer should be in
5. Explains what operation they need to perform to get the final answer

Give them everything except the actual final calculated number. They should only need to do one simple calculation. Write 5-7 sentences showing the complete setup.''',
                    system_content="You are an encouraging math tutor who provides clear, detailed hints. Be specific and use concrete examples from the problem. Never give the final answer, but guide students step-by-step. Use simple language and be thorough. IMPORTANT: Do NOT use LaTeX formatting. Do NOT use \\( \\), \\[ \\], $, or any backslash commands. Write all math using plain text with symbols like ×, ÷, ², ³, etc. For example, write 'w + 5' not '\\( w + 5 \\)', and write 'Area = length × width' not '\\text{Area} = \\text{length} \\times \\text{width}'. Write variables and numbers directly without any special formatting.",
                    temperature=0.7)

    ])


class Migration(migrations.Migration):

    dependencies = [
        ("math_tutor", "0005_seed_solvemessage"),
    ]

    operations = [
        migrations.RunPython(seed_generate_hint_reference_data),
    ]
