# Generated by Django 5.1.15 on 2026-03-16 17:52

from django.db import migrations

def seed_solvemessage_reference_data(apps, schema_editor):
    ChatMessage = apps.get_model('math_tutor', 'ChatMessage')

    ChatMessage.objects.update_or_create(
        slug="solve-math-problem",
        defaults={
            "llm_model": "gpt-4o-mini",
            "system_content": "You generate short, checkable algebra checkpoint steps. Always return valid JSON.",
            "temperature": 0.2,
            "user_content": '''You are helping build "checkpoint" step practice for {topic} topics.

Given:
- Word problem: "{problem}"

Task:
1) Identify what the student should solve for (examples: "x", "y", or "x,y" for a system).
2) Produce 2 to 8 checkpoints that correctly move from the start equation(s) to the solution.
   - This must work for ANY topic (linear equations, systems by substitution/elimination, inequalities, quadratic solving, rational/radical equations, etc.).
3) Each step must include:
   - instruction: a short imperative that describes the single transformation (e.g., "Subtract 25 from both sides", "Add the equations to eliminate y", "Factor the quadratic", "Take the square root of both sides")
   - checkpoint: the result *immediately after that step*
4) Format rules for checkpoints:
   - Plain text math only (no LaTeX environments).
   - For a system, represent multiple equations as a single string separated by commas, e.g. "x + y = 10, 2x - y = 3"
   - For inequalities, keep the inequality sign and direction (e.g., "x > 4").
   - Keep variable names consistent with the start equation(s).
5) CRITICAL VALIDATION: Each checkpoint MUST be mathematically correct:
   - Step 1 checkpoint must be a valid transformation from the start equation
   - Step 2 checkpoint must be a valid transformation from Step 1 checkpoint
   - And so on. Verify each step is correct before including it.
   - If you cannot verify a step is mathematically correct, do NOT include it.
6) If the start equation(s) are unclear or cannot be solved reliably, return steps: [].

Return ONLY valid JSON with EXACT keys:
{{
  "targetVariable": "x",
  "startEquation": "100 = 25 + 0.15x",
  "steps": [
    {{ "instruction": "Subtract 25 from both sides", "checkpoint": "75 = 0.15x" }},
    {{ "instruction": "Divide both sides by 0.15", "checkpoint": "500 = x" }}
  ],
  "finalAnswer": "x = 500"
}}
''',
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ("math_tutor", "0006_seed_generate_hint_1"),
    ]

    operations = [
        migrations.RunPython(seed_solvemessage_reference_data),
    ]
